import { cva, type VariantProps } from "class-variance-authority";
import type { ReactNode, ButtonHTMLAttributes } from "react";
import "./tokens/generated/variables.css";

/**
 * Primer Button — CVA variants consuming CSS custom properties from the d2c token pipeline.
 *
 * Figma source: component set 30258:5582
 *
 * All color, spacing, and typography values reference CSS custom properties
 * generated by Style Dictionary from DTCG token files. No hardcoded hex values.
 *
 * Layout: horizontal flex with in-flow leading/trailing visuals.
 * Font: system stack (no external font import needed).
 */

const buttonVariants = cva(
  [
    "primer-btn inline-flex items-center rounded-md border border-solid cursor-pointer select-none transition-colors duration-100",
    "font-[family-name:var(--primer-typography-button-font-family)]",
    "text-[length:var(--primer-typography-button-font-size)]",
    "leading-[var(--primer-typography-button-line-height)]",
    "font-[number:var(--primer-typography-button-font-weight)]",
    "gap-[var(--primer-spacing-button-gap)]",
  ].join(" "),
  {
    variants: {
      variant: {
        secondary:
          "bg-[var(--primer-color-button-default-background)] text-[var(--primer-color-text-primary)] border-[var(--primer-color-border-default)] shadow-[0_1px_0_0_rgba(31,35,40,0.04)] hover:bg-[var(--primer-color-button-default-hover)] active:bg-[var(--primer-color-button-default-active)]",
        primary:
          "bg-[var(--primer-color-button-primary-background)] text-[var(--primer-color-text-on-emphasis)] border-[var(--primer-color-border-transparent)] shadow-[0_1px_0_0_rgba(31,35,40,0.04)] hover:bg-[var(--primer-color-button-primary-hover)] active:bg-[var(--primer-color-button-primary-active)]",
        danger:
          "bg-[var(--primer-color-button-danger-background)] text-[var(--primer-color-button-danger-foreground)] border-[var(--primer-color-border-default)] shadow-[0_1px_0_0_rgba(31,35,40,0.04)] hover:bg-[var(--primer-color-button-danger-hover)] hover:text-[var(--primer-color-text-on-emphasis)] active:bg-[var(--primer-color-button-danger-active)] active:text-[var(--primer-color-text-on-emphasis)]",
        invisible:
          "bg-[var(--primer-color-button-invisible-background)] text-[var(--primer-color-button-outline-foreground)] border-[var(--primer-color-border-transparent)] shadow-none hover:bg-[var(--primer-color-button-invisible-hover)] active:bg-[var(--primer-color-button-invisible-active)]",
      },
      size: {
        sm: "h-[var(--primer-spacing-button-height-sm)] px-[var(--primer-spacing-button-padding-horizontal-sm)] text-xs",
        md: "h-[var(--primer-spacing-button-height-md)] px-[var(--primer-spacing-button-padding-horizontal)]",
        lg: "h-[var(--primer-spacing-button-height-lg)] px-[var(--primer-spacing-button-padding-horizontal)]",
      },
      alignContent: {
        center: "justify-center",
        start: "justify-start",
      },
      block: {
        true: "w-full",
        false: "",
      },
      disabled: {
        true: "bg-[var(--primer-color-button-disabled-background)] text-[var(--primer-color-text-disabled)] border-[var(--primer-color-border-default)] cursor-not-allowed opacity-50 hover:bg-[var(--primer-color-button-disabled-background)] active:bg-[var(--primer-color-button-disabled-background)]",
        false: "",
      },
    },
    defaultVariants: {
      variant: "secondary",
      size: "md",
      alignContent: "center",
      block: false,
      disabled: false,
    },
  }
);

export type ButtonVariants = VariantProps<typeof buttonVariants>;

export interface ButtonProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, "disabled">,
    ButtonVariants {
  label: string;
  leadingVisual?: ReactNode;
  trailingVisual?: ReactNode;
}

export function Button({
  label,
  leadingVisual,
  trailingVisual,
  variant,
  size,
  alignContent,
  block,
  disabled = false,
  className,
  ...props
}: ButtonProps) {
  return (
    <button
      className={buttonVariants({ variant, size, alignContent, block, disabled, className })}
      disabled={disabled || undefined}
      {...props}
    >
      {leadingVisual && (
        <span className="shrink-0 size-4 flex items-center justify-center overflow-clip">
          {leadingVisual}
        </span>
      )}
      <span className="whitespace-nowrap">{label}</span>
      {trailingVisual && (
        <span className="shrink-0 size-4 flex items-center justify-center overflow-clip">
          {trailingVisual}
        </span>
      )}
    </button>
  );
}

export { buttonVariants };
