/**
 * Token pipeline: DTCG JSON → CSS custom properties + TypeScript exports + Tailwind config
 *
 * Transforms each design system's pre-sourced token file using Style Dictionary.
 * Output goes to demo/button/{system}/tokens/generated/
 */
import StyleDictionary from "style-dictionary";
import { transformGroups, formats } from "style-dictionary/enums";
import { writeFileSync } from "node:fs";

const systems = [
  { name: "carbon", prefix: "cds" },
  { name: "primer", prefix: "primer" },
  { name: "polaris", prefix: "polaris" },
] as const;

async function buildTokens() {
  for (const system of systems) {
    console.log(`\nBuilding tokens for ${system.name}...`);

    const sd = new StyleDictionary({
      source: [`demo/button/${system.name}/tokens/button.tokens.json`],
      log: { warnings: "warn", verbosity: "default" },
      platforms: {
        css: {
          transformGroup: transformGroups.css,
          prefix: system.prefix,
          buildPath: `demo/button/${system.name}/tokens/generated/`,
          options: {
            outputReferences: true,
            usesDtcg: true,
          },
          files: [
            {
              destination: "variables.css",
              format: formats.cssVariables,
              options: {
                selector: `:root`,
              },
            },
          ],
        },
        ts: {
          transformGroup: transformGroups.js,
          prefix: system.prefix,
          buildPath: `demo/button/${system.name}/tokens/generated/`,
          options: {
            usesDtcg: true,
          },
          files: [
            {
              destination: "tokens.js",
              format: formats.javascriptEs6,
            },
          ],
        },
      },
    });

    await sd.buildAllPlatforms();

    // Generate Tailwind theme extension
    const tailwindTheme = generateTailwindConfig(system.prefix, system.name);
    const outPath = `demo/button/${system.name}/tokens/generated/tailwind-theme.js`;
    writeFileSync(outPath, tailwindTheme);
    console.log(`✓ ${system.name} tokens built (CSS + JS + Tailwind)`);
  }

  console.log("\nAll token builds complete.");
}

function generateTailwindConfig(prefix: string, system: string): string {
  return `/**
 * Tailwind CSS theme extension for ${system} design system.
 * Auto-generated by build-tokens — do not edit directly.
 *
 * Usage in tailwind.config.js:
 *   import { theme } from './demo/button/${system}/tokens/generated/tailwind-theme.js';
 *   export default { theme: { extend: theme } };
 */

export const theme = {
  colors: {
    '${prefix}-btn-primary': 'var(--${prefix}-color-button-primary-background)',
    '${prefix}-btn-primary-hover': 'var(--${prefix}-color-button-primary-hover)',
    '${prefix}-btn-primary-active': 'var(--${prefix}-color-button-primary-active)',
    '${prefix}-btn-secondary': 'var(--${prefix}-color-button-secondary-background)',
    '${prefix}-btn-secondary-hover': 'var(--${prefix}-color-button-secondary-hover)',
    '${prefix}-btn-danger': 'var(--${prefix}-color-button-danger-background)',
    '${prefix}-btn-danger-hover': 'var(--${prefix}-color-button-danger-hover)',
    '${prefix}-btn-disabled': 'var(--${prefix}-color-button-disabled-background)',
    '${prefix}-text-on-color': 'var(--${prefix}-color-text-on-color, var(--${prefix}-color-text-on-emphasis, var(--${prefix}-color-text-on-fill)))',
    '${prefix}-text-primary': 'var(--${prefix}-color-text-primary)',
  },
  spacing: {
    '${prefix}-btn-sm': 'var(--${prefix}-spacing-button-height-sm)',
    '${prefix}-btn-md': 'var(--${prefix}-spacing-button-height-md)',
    '${prefix}-btn-lg': 'var(--${prefix}-spacing-button-height-lg)',
  },
};
`;
}

buildTokens().catch((err) => {
  console.error("Token build failed:", err);
  process.exit(1);
});
