import { cva, type VariantProps } from "class-variance-authority";
import type { ReactNode, ButtonHTMLAttributes } from "react";
import "./tokens/generated/variables.css";

/**
 * Carbon Button — CVA variants consuming CSS custom properties from the d2c token pipeline.
 *
 * Figma source: component set 1854:1776
 *
 * All color, spacing, and typography values reference CSS custom properties
 * generated by Style Dictionary from DTCG token files. No hardcoded hex values.
 *
 * Layout: horizontal flex with in-flow icon (no absolute positioning).
 * Font: loaded via Google Fonts @import in Storybook preview CSS.
 */

const buttonVariants = cva(
  [
    "cds-btn inline-flex items-center overflow-clip cursor-pointer border-0",
    "font-[family-name:var(--cds-typography-button-font-family)]",
    "text-[length:var(--cds-typography-button-font-size)]",
    "leading-[var(--cds-typography-button-line-height)]",
    "tracking-[var(--cds-typography-button-letter-spacing)]",
    "font-[number:var(--cds-typography-button-font-weight)]",
  ].join(" "),
  {
    variants: {
      kind: {
        primary:
          "bg-[var(--cds-color-button-primary-background)] text-[var(--cds-color-text-on-color)] hover:bg-[var(--cds-color-button-primary-hover)] active:bg-[var(--cds-color-button-primary-active)]",
        secondary:
          "bg-[var(--cds-color-button-secondary-background)] text-[var(--cds-color-text-on-color)] hover:bg-[var(--cds-color-button-secondary-hover)] active:bg-[var(--cds-color-button-secondary-active)]",
        tertiary:
          "bg-[var(--cds-color-button-tertiary-background)] text-[var(--cds-color-text-interactive)] shadow-[inset_0_0_0_1px_var(--cds-color-border-interactive)] hover:bg-[var(--cds-color-button-tertiary-hover)] hover:text-[var(--cds-color-text-on-color)] hover:shadow-none active:bg-[var(--cds-color-button-tertiary-active)] active:text-[var(--cds-color-text-on-color)] active:shadow-none",
        ghost:
          "bg-transparent text-[var(--cds-color-text-interactive)] hover:bg-[var(--cds-color-button-ghost-hover)] active:bg-[var(--cds-color-button-ghost-active)]",
        "danger-primary":
          "bg-[var(--cds-color-button-danger-background)] text-[var(--cds-color-text-on-color)] hover:bg-[var(--cds-color-button-danger-hover)] active:bg-[var(--cds-color-button-danger-active)]",
        "danger-tertiary":
          "bg-transparent text-[var(--cds-color-button-danger-background)] shadow-[inset_0_0_0_1px_var(--cds-color-button-danger-background)] hover:bg-[var(--cds-color-button-danger-background)] hover:text-[var(--cds-color-text-on-color)] hover:shadow-none active:bg-[var(--cds-color-button-danger-active)] active:text-[var(--cds-color-text-on-color)] active:shadow-none",
        "danger-ghost":
          "bg-transparent text-[var(--cds-color-button-danger-background)] hover:bg-[var(--cds-color-button-ghost-hover)] active:bg-[var(--cds-color-button-ghost-active)]",
      },
      size: {
        xs: "h-6 items-center",
        sm: "h-[var(--cds-spacing-button-height-sm)] items-center",
        md: "h-[var(--cds-spacing-button-height-md)] items-center",
        lg: "h-[var(--cds-spacing-button-height-lg)] items-center",
        xl: "h-[var(--cds-spacing-button-height-xl)] items-start pt-4",
        "2xl": "h-[var(--cds-spacing-button-height-2xl)] items-start pt-4",
        expressive: "h-[var(--cds-spacing-button-height-lg)] items-center text-base leading-[22px] tracking-normal",
      },
      type: {
        default: "pl-[var(--cds-spacing-button-padding-horizontal)] pr-16 gap-2",
        "icon-only": "justify-center items-center",
      },
      disabled: {
        true: "bg-[var(--cds-color-button-disabled-background)] text-[var(--cds-color-text-on-color-disabled)] cursor-not-allowed shadow-none hover:bg-[var(--cds-color-button-disabled-background)] active:bg-[var(--cds-color-button-disabled-background)]",
        false: "",
      },
    },
    compoundVariants: [
      { type: "icon-only", size: "xs", className: "size-6" },
      { type: "icon-only", size: "sm", className: "size-8" },
      { type: "icon-only", size: "md", className: "size-10" },
      { type: "icon-only", size: "lg", className: "size-12" },
      { type: "icon-only", size: "xl", className: "size-16" },
      { type: "icon-only", size: "2xl", className: "size-20" },
      { type: "icon-only", size: "expressive", className: "size-12" },
    ],
    defaultVariants: {
      kind: "primary",
      size: "lg",
      type: "default",
      disabled: false,
    },
  }
);

export type ButtonVariants = VariantProps<typeof buttonVariants>;

export interface ButtonProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, "type" | "disabled">,
    ButtonVariants {
  label: string;
  icon?: ReactNode;
}

export function Button({
  label,
  icon,
  kind,
  size,
  type = "default",
  disabled = false,
  className,
  ...props
}: ButtonProps) {
  const isIconOnly = type === "icon-only";

  return (
    <button
      className={buttonVariants({ kind, size, type, disabled, className })}
      disabled={disabled || undefined}
      {...props}
    >
      {!isIconOnly && (
        <span className="whitespace-nowrap">{label}</span>
      )}
      {icon && (
        <span className="size-[var(--cds-spacing-button-icon-size)] shrink-0 flex items-center justify-center">
          {icon}
        </span>
      )}
    </button>
  );
}

export { buttonVariants };
