import { cva, type VariantProps } from "class-variance-authority";
import type { ReactNode, ButtonHTMLAttributes } from "react";
import "./tokens/generated/variables.css";

/**
 * Polaris Button — CVA variants consuming CSS custom properties from the d2c token pipeline.
 *
 * Figma source: component set 37:12833
 *
 * All color, spacing, and typography values reference CSS custom properties
 * generated by Style Dictionary from DTCG token files. No hardcoded hex values.
 *
 * Layout: horizontal flex with in-flow icon.
 * Font: Inter, loaded via Google Fonts @import in Storybook preview CSS.
 */

const buttonVariants = cva(
  [
    "polaris-btn inline-flex items-center justify-center overflow-clip border-0 cursor-pointer select-none transition-all duration-100",
    "font-[family-name:var(--polaris-typography-button-font-family)]",
    "text-[length:var(--polaris-typography-button-font-size)]",
    "leading-[var(--polaris-typography-button-line-height)]",
    "font-[number:var(--polaris-typography-button-font-weight)]",
    "rounded-[var(--polaris-spacing-button-border-radius)]",
    "gap-[var(--polaris-spacing-button-gap)]",
    "px-[var(--polaris-spacing-button-padding-horizontal)]",
    "py-1.5",
  ].join(" "),
  {
    variants: {
      variant: {
        auto: "bg-white text-[var(--polaris-color-text-primary)] shadow-[inset_0px_-1px_0px_0px_var(--polaris-color-border-secondary),inset_0px_0px_0px_1px_rgba(0,0,0,0.1),inset_0px_0.5px_0px_1.5px_white]",
        primary: "text-[var(--polaris-color-text-on-fill)] shadow-[inset_0px_-1px_0px_1px_rgba(0,0,0,0.8),inset_0px_0px_0px_1px_var(--polaris-color-button-primary-background),inset_0px_0.5px_0px_1.5px_rgba(255,255,255,0.25)]",
        tertiary: "bg-[var(--polaris-color-button-tertiary-background)] text-[var(--polaris-color-text-primary)] shadow-none hover:bg-[var(--polaris-color-button-tertiary-hover)] active:bg-[var(--polaris-color-button-tertiary-active)]",
      },
      tone: {
        neutral: "",
        critical: "",
      },
      iconOnly: {
        true: "gap-0 p-1.5",
        false: "",
      },
      disabled: {
        true: "text-[var(--polaris-color-text-disabled)] shadow-none cursor-not-allowed",
        false: "",
      },
    },
    compoundVariants: [
      {
        variant: "primary",
        tone: "neutral",
        disabled: false,
        className: "bg-[var(--polaris-color-button-primary-background)]",
      },
      {
        variant: "primary",
        tone: "critical",
        disabled: false,
        className: "bg-[var(--polaris-color-button-critical-background)] shadow-[inset_0px_-1px_0px_1px_rgba(142,11,33,0.8),inset_0px_0px_0px_1px_rgba(163,10,36,0.8),inset_0px_0.5px_0px_1.5px_rgba(247,128,134,0.64)]",
      },
      {
        variant: "auto",
        tone: "critical",
        disabled: false,
        className: "text-[var(--polaris-color-text-critical)]",
      },
      {
        variant: "tertiary",
        tone: "critical",
        disabled: false,
        className: "text-[var(--polaris-color-text-critical)]",
      },
      {
        variant: "auto",
        disabled: true,
        className: "bg-[var(--polaris-color-button-disabled-background)]",
      },
      {
        variant: "primary",
        disabled: true,
        className: "bg-[var(--polaris-color-button-disabled-background)]",
      },
      {
        variant: "tertiary",
        disabled: true,
        className: "bg-[var(--polaris-color-button-disabled-background)]",
      },
    ],
    defaultVariants: {
      variant: "auto",
      tone: "neutral",
      iconOnly: false,
      disabled: false,
    },
  }
);

export type ButtonVariants = VariantProps<typeof buttonVariants>;

export interface ButtonProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, "disabled">,
    ButtonVariants {
  label: string;
  icon?: ReactNode;
}

export function Button({
  label,
  icon,
  variant = "auto",
  tone,
  iconOnly,
  disabled = false,
  className,
  ...props
}: ButtonProps) {
  const isPrimary = variant === "primary" && !disabled;
  const gradientStyle: React.CSSProperties | undefined = isPrimary
    ? {
        backgroundImage:
          "linear-gradient(180deg, rgba(48,48,48,0) 63.5%, rgba(255,255,255,0.15) 100%)",
      }
    : undefined;

  return (
    <button
      className={buttonVariants({ variant, tone, iconOnly, disabled, className })}
      disabled={disabled || undefined}
      style={gradientStyle}
      {...props}
    >
      {iconOnly
        ? icon && <span className="size-5 flex items-center justify-center">{icon}</span>
        : (
          <>
            {icon && <span className="shrink-0 size-4 flex items-center justify-center">{icon}</span>}
            <span className="whitespace-nowrap">{label}</span>
          </>
        )
      }
    </button>
  );
}

export { buttonVariants };
